### ISSUE TITLE
Depreciated dependencies warnings

### ISSUE THREAD

**Issue by grctest** [bitshares/open-explorer#5]
Running Ubuntu 17.10, installed NVM & set it to 'stable' which provides node v9.5.0 (npm v5.6.0).

I got the following warnings upon `npm install`:

```
npm install
npm WARN deprecated bower@1.8.2: ...psst! Your project can stop working at any moment because its dependencies can change. Prevent this by migrating to Yarn: https://bower.io/blog/2017/how-to-migrate-away-from-bower/
npm WARN deprecated coffee-script@1.10.0: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)
npm WARN deprecated http2@3.3.7: Use the built-in module in node 9.0.0 or newer instead
npm WARN deprecated jade@1.11.0: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated transformers@2.1.0: Deprecated, use jstransformer
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm WARN lifecycle bitshares-explorer@0.0.0~postinstall: cannot run in wd %s %s (wd=%s) bitshares-explorer@0.0.0 bower install /root/open-explorer-hertz.network
```

Could be worth updating these packages? https://github.com/oxarbitrage/open-explorer/blob/master/package.json

Cheers 👍

**Comment by oxarbitrage** [comment]
Most of the packages in there can probably be updated to newer versions. However it need to be tested one by one and make sure everything remains working. I know for example the explorer fails with bootstrap 4(last version - dependency from bower, not from node) so it is using bootstrap 3.

**Comment by grctest** [comment]
Regarding:
`npm WARN lifecycle bitshares-explorer@0.0.0~postinstall: cannot run in wd %s %s (wd=%s) bitshares-explorer@0.0.0 bower install /root/open-explorer-hertz.network`

https://github.com/npm/npm/issues/3497#issuecomment-23966536 Turns out this warning is because I'm running this as root instead of as a secondary user.

Workarounds:
* Use a non-root user.
* Disregard concerns & use `npm install --unsafe-perm`

**Comment by oxarbitrage** [comment]
if the postinstall works the `bower install` is not needed. to run bower as root use `bower install --allow-root`

**Comment by grctest** [comment]
Using a non-root user solved the post install problem.

**Comment by oxarbitrage** [comment]
All dependencies are in the last version, this is an old one. closing.
