### ISSUE TITLE
Whitelist operation doesn't show

### ISSUE THREAD

**Issue by abitmore** [bitshares/open-explorer#58]
Not sure if it's fixed..

https://bitsharestalk.org/index.php?topic=28162

![image](https://user-images.githubusercontent.com/9946777/63637239-aa7ae000-c67a-11e9-965a-82faa30da5bf.png)

**Comment by oxarbitrage** [comment]
Yes, this was fixed

![whitelist](https://user-images.githubusercontent.com/21685097/63637399-fb2a1300-c651-11e9-96a3-3e8e7857d2f1.png)

https://open-explorer.io/#/operations/1.11.725010884
